"""empty message

Revision ID: 1a7879dde723
Revises: fdb05c6a9631
Create Date: 2019-12-02 22:50:32.718093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a7879dde723'
down_revision = 'fdb05c6a9631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notes', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notes')
    # ### end Alembic commands ###
